# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Structure+Strangeness
#email: your-email@example.com
description: #>- # this means to ignore newlines until "baseurl:"
  <img src="aaron_sfi_close_sm.jpg" alt="Aaron Clauset" height="159" width="144"><br/>
  By <b>Aaron Clauset</b><br/>
  Professor of Computer Science, <br/>
  Core Faculty in the BioFrontiers Institute, <br/>
  University of Colorado Boulder and, <br/>
  External Faculty at the Santa Fe Institute <br/>
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaronclauset.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aaronclauset
github_username: aaronclauset

# Build settings
#markdown: kramdown
theme: jekyll-theme-minimal
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
